Initial commit
Experiment with http-sig and I'm getting the following error:

 wink@3900x:~/prgs/rust/projects/expr-http-sig (main)
 $ cargo build
    Compiling expr-http-sig v0.1.0 (/home/wink/prgs/rust/projects/expr-http-sig)
 error[E0599]: the method `signed` exists for struct `reqwest::blocking::Request`, but its trait bounds were not satisfied
   --> src/main.rs:18:10
    |
 18 |         .signed(&config)
    |          ^^^^^^ method cannot be called on `reqwest::blocking::Request` due to unsatisfied trait bounds
    |
   ::: /home/wink/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.2/src/blocking/request.rs:20:1
    |
 20 | pub struct Request {
    | ------------------
    | |
    | doesn't satisfy `reqwest::blocking::Request: ClientRequestLike`
    | doesn't satisfy `reqwest::blocking::Request: http_sig::SigningExt`
    |
    = note: the following trait bounds were not satisfied:
            `reqwest::blocking::Request: ClientRequestLike`
            which is required by `reqwest::blocking::Request: http_sig::SigningExt`
            `&reqwest::blocking::Request: ClientRequestLike`
            which is required by `&reqwest::blocking::Request: http_sig::SigningExt`
            `&mut reqwest::blocking::Request: ClientRequestLike`
            which is required by `&mut reqwest::blocking::Request: http_sig::SigningExt`

 error: aborting due to previous error

 For more information about this error, try `rustc --explain E0599`.
 error: could not compile `expr-http-sig`

 To learn more, run the command again with --verbose.